sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.1
  - 2.3.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
cache: bundler
script:
  - bundle exec rspec
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile
