sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.1
  - 2.3.3
addons:
  postgresql: '10'
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
cache: bundler
gemfile:
  - gemfiles/Gemfile.rails-4.2.rb
  - gemfiles/Gemfile.rails-5.0.rb
  - gemfiles/Gemfile.rails-5.1.rb
  - gemfiles/Gemfile.rails-5.2.rb
